spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


security:
  jwt:
    secret: ${JWT_ACCESS_SECRET}


logging:
  level:
    org:
      springframework:
        security:
          DEBUG